repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: '(waveshare_epd|scripts)/.*'
      # Run the formatter.
      - id: ruff-format
        exclude: '(waveshare_epd|scripts)/.*'
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
    -   id: markdownlint
        args: ["--disable=MD013"]
    -   id: markdownlint-fix
        args: ["--disable=MD013", "--fix"]
